### ISSUE TITLE
Confusing documentation around single/multi consumer

### ISSUE THREAD

**Issue by kvark** [hawkw/thingbuf#67]
- `ThingBuf` documentation - "A fixed-size, lock-free, multi-producer multi-consumer (MPMC) queue."
- The [original algorithm](https://www.1024cores.net/home/lock-free-algorithms/queues/bounded-mpmc-queue) is MPMC
- Readme description: "I’m at the buffer pool. I’m at the MPSC channel. I’m at the combination MPSC channel and buffer pool."
- Loom models are called "mpsc_xxx"

**Comment by hawkw** [comment]
The `ThingBuf` type is a MPMC queue. The channels in `thingbuf::mpsc` are, as the module name suggests, MPSC. MPMC channel types could also be implemented, by using a second linked list for recv waiters, rather than a single waiter cell; I haven't written one yet because I didn't need an MPMC channel.

Loom models have names beginning with `mpsc_` or `mpmc_` depending on whether they simulate a single- or multi-consumer scenario.
